server:
        port: 8395

spring:
     application:
         name: quartz-demo
     datasource:
         driver-class-name: com.mysql.jdbc.Driver
         #任意填写数据库信息,Quartz数据库连接信息在quartz.properties
         url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
         username: root
         password: 123456
     jpa:
         hibernate:
             ddl-auto: validate
             show-sql: true
logging:
    file: logback.xml
